tap "homebrew/bundle"

# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Fast, disk space efficient package manager
brew "pnpm"
# Organize software neatly under a single directory tree (e.g. /usr/local)
brew "stow"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Manage multiple Node.js versions
brew "nvm"
# Opensource IDE for exploring and testing api's
cask "bruno"
# Terminal emulator that uses platform-native UI and GPU acceleration
cask "ghostty"
# Clipboard manager
cask "maccy"
# Tool to control external monitor brightness & volume
cask "monitorcontrol"
# Collaboration platform for API development
cask "postman"
# Move and resize windows using keyboard shortcuts or snap areas
cask "rectangle"
# Tool to reverse the direction of scrolling
cask "scroll-reverser"
