#!/usr/bin/env bash
set -e

# This script runs some static analysis tools against our code base.
# To only run the static analysis tools against the services that
# have been changed in the current branch use the following:
#   ./bin/_run_rpcmap --diff

if [ "$1" == "--diff" ]; then
  echo -e "⏱  Finding services modified in branch"
  TESTABLE="$(aps --include-dependencies=false)"
  if echo "$TESTABLE" | grep -E --quiet '^(bedrock|libraries/)'; then
      # If there's a change to libraries run rpcmap against all dependencies to avoid a situation
      # where a library adds an rpc but the services which import it don't have the rule
      # see #inc-firehose-publish-errors-2023-10-16 for example
      echo -e "⏱  Finding dependencies of modified services due to change in libraries"
      TESTABLE="$(aps --include-dependencies=true)"
  fi
else
   echo -e "⏱  Running against all services"
  TESTABLE=$(find -- * -maxdepth 1 -type d -a \( \
      -name 'edge-proxy*' -o \
      -name 'cron.*' -o \
      -name 'service.*' -o \
      -name 'bedrock' -o \
      -name 'ingress-*' -o \
      -wholename 'libraries/*' -o \
      -wholename 'staff-vpn/*' \
      \) | sort)
fi

TESTABLE=$(for dir in $TESTABLE
  do
    if [ "$(find "${dir}" -name '*.go' | wc -l)" -gt 0 ];then
      echo "${dir}"
    fi
    if [[ ${dir} == cron.* ]];then
      echo "${dir}"
    fi
  done
  )

# This is required otherwise if there is nothing to test it tests
# everything
if [ "$TESTABLE" == "" ] ; then
 echo -e "Nothing to test, exiting"
 exit 0
fi

echo -e "Running tests against:"
echo "${TESTABLE}"

EXIT=0
echo -e "⏱  Checking cronjobs"
while read -r dir; do
  if [[ ${dir} != cron.* ]];then
    # not a cronjob
    continue
  fi

  if service=$(grep -Roh "Host: service\..*" "${dir}");then
    if ! ls "${dir}"/manifests/egress/*.rule >/dev/null 2>/dev/null;then
      echo "${dir} has no egress rules but appears to call service(s) ${service}"
      EXIT=1
    fi
  fi
  # else it doesn't look like the cron job calls any services (so doesn't need any egress rules)
done <<< "$TESTABLE"

echo -e "⏱  Running rpcmap"
rpcmap_dirs=()
while read -r dir; do
  top_level_dir=$(echo "$dir" | awk -F'/' '{ print $1 }')
  if [ -f "$top_level_dir/main.go" ]; then
    # For the purposes of rpcmap, we say top level directories with a main.go are a service
    rpcmap_dirs+=("$top_level_dir")
  fi
done <<< "$TESTABLE"

# Only check if we actually found anything
NUM_SERVICES_PER_RPCMAP="15"

# Check if "service.acceptance-tests" is in rpcmap_dirs, if so skip, then remove it
# This is because rpcmap sometimes killed in CI when checking acceptance tests with other services.
# We suspect it is running out of memory.
# This also happens in `bin/_run_static_analysis`
for i in "${!rpcmap_dirs[@]}"; do
  if [[ ${rpcmap_dirs[i]} == "service.acceptance-tests" ]]; then
    echo "rpcmap is skipping service.acceptance-tests"
    unset 'rpcmap_dirs[i]'
    break
  fi
done

if [ ${#rpcmap_dirs[@]} -gt 0 ]; then
  read -r -a uniq_rpcmap_dirs <<< "$(echo "${rpcmap_dirs[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' ')"
  echo "rpcmap is generating: ${uniq_rpcmap_dirs[*]}"
  rpcmap_packages=$(printf "%s\n" "${uniq_rpcmap_dirs[@]}" | awk '{print "github.com/monzo/wearedev/" $1}')
  echo "$rpcmap_packages" | xargs -n "$NUM_SERVICES_PER_RPCMAP" rpcmap -generate || {
    echo "Make sure you are using an up-to-date version of rpcmap by running:"
    echo "tools/install -f rpcmap"
    echo ""
    echo "Then, run this and commit the result:"
    echo "$rpcmap_packages" | xargs -n "$NUM_SERVICES_PER_RPCMAP" echo "rpcmap -generate"
    exit 1
  }
else
  echo "rpcmap found no services to check!"
fi

exit $EXIT
